### ISSUE TITLE
RSyntaxTextArea themes not working with 3.0.0

### ISSUE THREAD

**Issue by GraxCode** [weisJ/darklaf-extensions#1]
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: com/github/weisj/darklaf/util/DarkUIUtil
	at com.github.weisj.darklaf.extensions.rsyntaxarea.DarklafIconGroup.getIcon(DarklafIconGroup.java:44)
	at org.fife.ui.rtextarea.RTextArea.setIconGroup(RTextArea.java:1517)
	at com.github.weisj.darklaf.extensions.rsyntaxarea.DarklafRSyntaxTheme.apply(DarklafRSyntaxTheme.java:92)

**Comment by weisJ** [comment]
Fixed with version `0.4.0`
